### PR TITLE
Add trespass map

### PR DESCRIPTION
**Pull request by fedefernandez**
Hi @Nick-Hansen 

First of all, thanks for this great application. I'm always using it in my IA games because I always forget how to calculate the LoS properly 😂 

I'm trying to complete your maps with the Jabba's Realm campaign. I started with the Trespass mission, but I'm struggling with the blocking edges and intersections. See the image below:

Screenshot 2023-09-29 at 18 34 23

Could you help me with that? I have all the images available, please let me know if this is useful at all.

### CODE REVIEW

**Comment by Nick-Hansen** [comment]
Hello Fede!

Thank you so much for being the first person to show interest in
contributing! This has been a fun project and I'm glad you are finding it
useful! I had the same issue, which is why I started the project.

Please let me share a branch that will help you create maps. I made it
after the first several, and it helps a great deal. It let's you load a
picture of your map, set the width and length, select your map Element, and
click to place in the right spot. It shows up brightly on the map, so you
can easily see points you've already created.

For your specific question right now, this is what you would use for this
example. The top left corner is always point 0,0. In this example im
leaving out the partial squares when counting points for this example. I
don't have the exact code, but you would need something like this:
Intersections: [
  {
    x:2,
    y:2,
    connections: [
      {
        x: 1,
        y: 2
      },
      {
        x:3,
        y:2
      },
      {
        x:2,
        y:3
      }
    ]
  },
  {
    x:2,
    y:5,
    connections: [
      {
        x:1,
        y:5
      },
      {
        x:2,
        y:6
      },
      {
        x:3,
        y:5
      }
    ]
  },
  {
    x:3,
    y:5,
    connections: [
      {
        x:2,
        y:5
      },
      {
        x:4,
        y:5
      }
    ]
  },
  {
    x:4,
    y:5,
    connections: [
      {
        x:3,
        y:5
      },
      {
        x:5,
        y:5
      }
    ]
  },
  {
    x:4,
    y:5,
    connections: [
      {
        x:3,
        y:5
      },
      {
        x:5,
        y:5
      }
    ]
  },
  {
    x:5,
    y:5,
    connections: [
      {
        x:4,
        y:5
      },
      {
        x:6,
        y:5
      }
    ]
  },
  {
    x:6,
    y:5,
    connections: [
      {
        x:6,
        y:4
      },
      {
        x:5,
        y:5
      },
      {
        x:6,
        y:6
      }
    ]
  }
]

The order of intersections and connections within intersections don't
really matter. The interection has the point of origin, and the connections
are each point it reaches out to.

I will send you the branch to help with this when I get to my computer
later tonight!

Best wishes,
Nick Hanse

**Comment by fedefernandez** [comment]
Great news! Looking forward to see that branch's code in action. I'll work with your code this week. Thanks!

**Comment by Nick-Hansen** [comment]
Hello Fede!

I'm so sorry I haven't gotten back to you. Things were pretty busy after we
got back from vacation.

I can't reply with all the information I'd like in this response. Can you
please give me an email address to mail you the instructions?

Thanks very much for your help on this project!
Nick Hansen
***@***.***

**Comment by fedefernandez** [comment]
Hi @Nick-Hansen

I've finally found the time to get through your emails and prepare the first map. The following ones should be easier and faster to do, but I prefer to start with just one. The utility branch is really helpful.

**Comment by Nick-Hansen** [comment]
That's great, Fede!

I didn't want to pressure you, but I was wondering how everything was
going. It definitely gets much faster once you're used to the process. The
longest part for me is cropping the map image.

It is difficult to test the map without being able to check in. If changes
are needed after merge, there is a load button so we don't have to start
from scratch.

I'll check out your changes as soon as I can.

Thanks so much for your contributions!
Nick

**Review by Nick-Hansen — APPROVED** [review]
This is great work Fede! There are a couple more changes we'll need in order to see your maps in the UI. I'll put those in, and you can follow that for reference on your next maps.

**Pull request merged**
